### ISSUE TITLE
Restore point back to its original location

### ISSUE THREAD

**Issue by tuhdo** [nivekuil/corral#1]
I suggest that you should wrap your code in `save-excursion`. That way, it causes minimal distraction and I can resume typing my current symbol without hassle.

**Comment by nivekuil** [comment]
Thanks for the suggestion! The benefit of moving the point along with the delimiters is that you're set up to navigate around by sexp, but preserving the point is definitely more convenient in many cases. Do you think this should be an option set through a variable, or a separate command entirely? Alternatively, the simplest way to do this would be to call `(push-mark)` before the wrap, and have the user call `(pop-to-mark-command` to get back.

**Comment by tuhdo** [comment]
I think it's better to use a custom variable and not adding to the mark ring, since this is a frequent operation. You can do something like this:

``` elisp
(defcustom corral-follow-delimiter nil
  "Follow delimiter as it is inserted."
  :type 'boolean)

(defun corral-parentheses-forward ()
  "Wrap parentheses around sexp, moving point to the closing parentheses."
  (interactive)
  (let (end-point)
    (save-excursion
      (if (or (eq last-command 'corral-parentheses-forward)
              (eq last-command 'corral-parentheses-backward))
          (corral-shift-forward ?( ?))
        (corral-wrap-forward ?( ?)))
      (setq end-point (point)))
    (when corral-follow-delimiter
      (goto-char end-point))))
```

With that, you can insert forward/backward delimiter with minimal distraction.

**Comment by nivekuil** [comment]
I added the defcustom `corral-preserve-point`, just set that to `t` and it'll work as you describe. Thanks for all your help!

**Comment by nivekuil** [comment]
I added the defcustom `corral-preserve-point`, just set that to `t` and it'll work as you describe. Thanks for all your help!

**Comment by tuhdo** [comment]
Instead of using `(when (not corral-preserve-point)...)`, you can simply use `(unless corral-preserve-point ...)`.

**Comment by nivekuil** [comment]
Ah, I figured there had to be a better way to write that. Thanks :)

**Comment by ReneFroger** [comment]
Thanks, I was looking for this feature too!
