### ISSUE TITLE
Feature request: Curly braces

### ISSUE THREAD

**Issue by jplindstrom** [nivekuil/corral#2]
Have you though about adding curly braces?

For instance in Perl it's quite common to type something, then realizing you need to dereference it and wrap it in {}. 

Another case is string interpolation in shell scripts that sometimes need bracing.

Curly braces are also used to interpolate inside Ruby strings.

**Comment by nivekuil** [comment]
Sure, it's pretty trivial to add. I don't write perl, so feel free to let me know how well it works. The commands are called `corral-braces-forward` and `corral-braces-backward`. Thanks for the suggestion!

**Comment by jplindstrom** [comment]
Tremendous mate! Many thanks!
