### ISSUE TITLE
suggestion: make a local map

### ISSUE THREAD

**Issue by QiangF** [nivekuil/corral#6]
Hello Sir,
Can you  make corral behave like this:

M-] run corral-brackets-forward, immeadiatly after that command ] run corral-brackets-forward again and [ run the backward version. C-g exit the command.
So that you don't need to press M if you want to forward several words.

For quote:
M-" run double quote forward, M-" again cancel the previous forward and do double quote backward, after that " continue forwarding and ' continue backwarding.

make the same for M-'

I am not good at elisp, maybe you can find example in expand-region and hydra.
Thank you!

**Comment by nivekuil** [comment]
Is it difficult to keep meta held down while you're pressing the keys? It seems disruptive to the text editing flow to make the user C-g out of the command.

**Comment by QiangF** [comment]
Or maybe use meta to exit? 
Feel free to close this issue.

**Comment by nivekuil** [comment]
I don't think it's possible to bind a modifier key to anything by itself, but if you keep it held down, releasing the key is basically the same as ending the sequence.
