### ISSUE TITLE
corral-wrap-backward: Wrong type argument: characterp, nil

### ISSUE THREAD

**Issue by Poquaruse** [nivekuil/corral#7]
Hi,

Thanks for this nice helper! I'm experiencing some issues in Emacs 25 (GNU Emacs 25.0.50.1 (i686-pc-mingw32) of 2015-10-25). 

To reproduce:
- create new buffer
- type "asdf asdf asdf"
- M-x "corral-parantheses-backward"
  --> "corral-wrap-backward: Wrong type argument: characterp, nil"

However, if I enter a space and go back one space (C-b) then it does work again?!

Any ideas? Can I help somehow?

Thanks again and best regards

**Comment by nivekuil** [comment]
Thanks for the report, and for using the package. 5b40cfa52ee0d11fd30789b3bdd842e788760c35 should fix it - the issue is that it wasn't handling the case where (char-after) and (char-before) could be nil, like at the very end of the file.

**Comment by Poquaruse** [comment]
Great, thank you for the very quick fix! :-)
