### ISSUE TITLE
Feature request: backquote sign

### ISSUE THREAD

**Issue by ReneFroger** [nivekuil/corral#8]
Thanks for sharing this awesome package. Would it be possible to add backquote support (I cannot display it here, because it's formatted by Github) ? I use it a lot in Markdown and ReStructuredText filetypes. (See also http://www.computerhope.com/jargon/b/backquot.htm)

Thank you in advance!

**Comment by nivekuil** [comment]
Thanks for still using the package! Added with 9a5ab7f293a23a4fec77ab4fb442d69ecfcc293f. Also, you can type a backquote if you escape it with a backslash first: \`

**Comment by ReneFroger** [comment]
After upgrading packages with Paradox, I just `tested` it, and it works fine!

Thanks for your support!
