### ISSUE TITLE
Corral doesn't include exclamation mark?

### ISSUE THREAD

**Issue by ReneFroger** [nivekuil/corral#9]
As long time user of Corral, I love it! Thanks for that! It seems I found something
that might be a bug. To reproduce, `[]` stands for the cursor

```
foobar![]
```

Then I call <kbd>M-x</kbd> corral-backquote-backward, which is bound to a key by the way.

But it includes only the characters in a quote mark, without the `!` exclaimation mark.

**Comment by nivekuil** [comment]
If you try `forward-sexp` starting at the beginning of `foobar!` then you'll see that it skips the exclamation point - this is just how emacs parses sexps. You can get around this by customizing `corral-syntax-entries`, which temporarily changes the major mode's syntax table for the purpose of the corral operation. In this case, something like

```
(add-to-list 'corral-syntax-entries '(?! "_"))
```

should get it working the way you want. Thanks for using the package!

**Comment by ReneFroger** [comment]
That solved it, thanks for your help!
